name: Build Verification

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build success
        run: npm run verify-build

      - name: Check build status and lock merge
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: checks } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              status: 'completed',
            });

            const buildCheck = checks.check_runs.find((check) => check.name === 'Build project');
            if (buildCheck && buildCheck.conclusion === 'success') {
              console.log('Build passed. Allowing merge.');
            } else {
              console.log('Build failed. Blocking merge.');
              github.pullRequests.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                state: 'closed',
              });
              core.setFailed('Build failed. Merge is blocked.');
            }
